"use strict";
exports.__esModule = true;
var g = true;
var y = 'strick mode';
var x2 = 2;
var He = 'Hello World';
var message = 'Xin Chào';
console.log(message);
var x = 100.2;
var ex = 10 / 2;
var ta = 'rararara';
var sum;
sum = 3 + 6;
var kieubool = true;
var total = 0;
var stringa = 'Google';
var as = 5;
var t = '10.2GF';
var gi = 'hello World';
console.log(t + '  ' + stringa);
